name: flutter_application_cash
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  date_picker_timeline: ^1.2.3
  flutter:
    sdk: flutter
  flutter_date_picker_timeline: ^0.3.3
  gap: ^3.0.1
  json_annotation: ^4.8.1
  google_fonts: ^6.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.0.5
  intl: ^0.17.0
  lottie: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
